// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf5MvlK_09509PKM71j5VUX52fmLNn9aI',
    appId: '1:970196382113:web:e79427f21cc3b8d4cfdbe0',
    messagingSenderId: '970196382113',
    projectId: 'to-do-list-17ced',
    authDomain: 'to-do-list-17ced.firebaseapp.com',
    storageBucket: 'to-do-list-17ced.firebasestorage.app',
    measurementId: 'G-X88BB2KF6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8O5OW9oy9EtCTNOLXX2bwaxgXqlBo2RA',
    appId: '1:970196382113:android:8fb7b3f4fc07aeddcfdbe0',
    messagingSenderId: '970196382113',
    projectId: 'to-do-list-17ced',
    storageBucket: 'to-do-list-17ced.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf5MvlK_09509PKM71j5VUX52fmLNn9aI',
    appId: '1:970196382113:web:c83287cffeb11541cfdbe0',
    messagingSenderId: '970196382113',
    projectId: 'to-do-list-17ced',
    authDomain: 'to-do-list-17ced.firebaseapp.com',
    storageBucket: 'to-do-list-17ced.firebasestorage.app',
    measurementId: 'G-83J9C2FPFB',
  );
}
